# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

inhibit_all_warnings!

target 'InnCloud' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InnCloud

  pod 'SnapKit'
  
  pod 'LLDebugToolSwift' ,:configurations => ['Debug']

  target 'InnCloudTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'InnCloudUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
